# Generated by Django 3.2 on 2021-05-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagina', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pagina',
            options={'ordering': ('-created',), 'verbose_name': 'pagina', 'verbose_name_plural': 'paginas'},
        ),
        migrations.AddField(
            model_name='pagina',
            name='autor',
            field=models.CharField(default='admins', max_length=150, verbose_name='periodista'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='image',
            field=models.ImageField(null=True, upload_to='images', verbose_name='Imagen'),
        ),
        migrations.AddField(
            model_name='pagina',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Última Edición'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Creado'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='texto',
            field=models.TextField(verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='pagina',
            name='titulo',
            field=models.CharField(max_length=150, verbose_name='Título'),
        ),
    ]
