# Generated by Django 3.2 on 2021-04-20 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anuncios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anuncio',
            old_name='update',
            new_name='updated',
        ),
    ]
